theme:
  name: 'material'
  logo: assets/logo-horizontal.png
  favicon: assets/favicon.png

site_name: Open Semantic Interchange
site_description: This is the website for the Open Semantic Interchange
copyright: © 2026- The Open Semantic Interchange Authors

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: 'index.md'
  - Spec: 'spec.md'
  - Documentation: '/docs/index.md'
  - GitHub: 'https://github.com/open-semantic-interchange'
  - Community: 'community.md'
  - Blog: 'blog.md'
